force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <label>Announcement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Box_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Roll_Count__c.field-meta.xml
<CustomField>
    <fullName>Roll_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Roll Count</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Box_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ONES</fullName>
        <label>Ones</label>
    </customValue>
    <customValue>
        <fullName>TWOS</fullName>
        <label>Twos</label>
    </customValue>
    <customValue>
        <fullName>THREES</fullName>
        <label>Threes</label>
    </customValue>
    <customValue>
        <fullName>FOURS</fullName>
        <label>Fours</label>
    </customValue>
    <customValue>
        <fullName>FIVES</fullName>
        <label>Fives</label>
    </customValue>
    <customValue>
        <fullName>SIXES</fullName>
        <label>Sixes</label>
    </customValue>
    <customValue>
        <fullName>MAX</fullName>
        <label>Max</label>
    </customValue>
    <customValue>
        <fullName>MIN</fullName>
        <label>Min</label>
    </customValue>
    <customValue>
        <fullName>TRIPS</fullName>
        <label>Trips</label>
    </customValue>
    <customValue>
        <fullName>STRAIGHT</fullName>
        <label>Straight</label>
    </customValue>
    <customValue>
        <fullName>BOAT</fullName>
        <label>Boat</label>
    </customValue>
    <customValue>
        <fullName>CARRIAGE</fullName>
        <label>Carriage</label>
    </customValue>
    <customValue>
        <fullName>YAMB</fullName>
        <label>Yamb</label>
    </customValue>
    <masterLabel>Box Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RecordUtil.cls
public with sharing class RecordUtil {
    public static Map<String, Object> recordToMap (String objectName, Object record) {
        Map<String, Object> returnMap = new Map<String, Object>();
        if (objectName == 'GAME') {
            Game__c game = (Game__c) record;
            returnMap.put('rollCount', game.Roll_Count__c);
            returnMap.put('announcement', game.Announcement__c);
            returnMap.put('dice', JSON.deserializeUntyped(game.Dice__c));
            returnMap.put('form', JSON.deserializeUntyped(game.Form__c));
        }
        return returnMap;
    }
}