force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <label>Announcement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Box_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game__c/fields/Roll_Count__c.field-meta.xml
<CustomField>
    <fullName>Roll_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Roll Count</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Sheet__c.field-meta.xml
<CustomField>
    <fullName>Sheet__c</fullName>
    <defaultValue>&apos;{}&apos;</defaultValue>
    <label>Sheet</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Box_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ONES</fullName>
        <label>Ones</label>
    </customValue>
    <customValue>
        <fullName>TWOS</fullName>
        <label>Twos</label>
    </customValue>
    <customValue>
        <fullName>THREES</fullName>
        <label>Threes</label>
    </customValue>
    <customValue>
        <fullName>FOURS</fullName>
        <label>Fours</label>
    </customValue>
    <customValue>
        <fullName>FIVES</fullName>
        <label>Fives</label>
    </customValue>
    <customValue>
        <fullName>SIXES</fullName>
        <label>Sixes</label>
    </customValue>
    <customValue>
        <fullName>MAX</fullName>
        <label>Max</label>
    </customValue>
    <customValue>
        <fullName>MIN</fullName>
        <label>Min</label>
    </customValue>
    <customValue>
        <fullName>TRIPS</fullName>
        <label>Trips</label>
    </customValue>
    <customValue>
        <fullName>STRAIGHT</fullName>
        <label>Straight</label>
    </customValue>
    <customValue>
        <fullName>BOAT</fullName>
        <label>Boat</label>
    </customValue>
    <customValue>
        <fullName>CARRIAGE</fullName>
        <label>Carriage</label>
    </customValue>
    <customValue>
        <fullName>YAMB</fullName>
        <label>Yamb</label>
    </customValue>
    <masterLabel>Box Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/models/Game.cls
public class Game {
    
    @AuraEnabled
    public Sheet gameSheet { get; private set; }

    @AuraEnabled
    public List<Dice> dices { get; private set; }

    @AuraEnabled 
    public Integer rollCount { get; private set; }

    public BoxType announcement { get; private set; }
    
    @AuraEnabled
    public transient String announcementString {
        get {
            return String.valueOf(announcement);
        }
        private set;
    }

    public GameStatus status { get; private set; }

    @AuraEnabled
    public transient String statusString {
        get {
            return String.valueOf(statusString);
        }
        private set;
    }

    private Game(Sheet gameSheet, List<Dice> dices, Integer rollCount, BoxType announcement, GameStatus status) {
        this.gameSheet = gameSheet;
        this.dices = dices;
        this.rollCount = rollCount;
        this.announcement = announcement;
        this.status = status;
    }

    public static Game getInstance() {
        return new Game(Sheet.getInstance(), generateDices(), 0, null, GameStatus.IN_PROGRESS);
    }

    public static Game fromSObject(Game__c game) {
        return new Game(
            (Sheet) JSON.deserialize(game.Sheet__c, Sheet.class),
            (List<Dice>) JSON.deserialize(game.Dices__c, List<Dice>.class),
            Integer.valueOf(game.Roll_Count__c),
            game.Announcement__c != null ? BoxType.valueOf(game.Announcement__c) : null,
            GameStatus.valueOf(game.Status__c)
        );
    }

    public Game__c toSObject(Game__c game) {
        game.Sheet__c = JSON.serialize(gameSheet);
        game.Dices__c = JSON.serialize(dices);
        game.Roll_Count__c = rollCount;
        game.Announcement__c = announcementString;
        game.Status__c = statusString;
        return game;
    }

    private static List<Dice> generateDices() {
        List<Dice> dices = new List<Dice>();
        for (Integer i = 0; i < GameConstants.DICE_LIMIT; i++) {
            dices.add(Dice.getInstance(i));
        }
        return dices;
    }

    public boolean isAnnouncementRequired { 
        get {
            return rollCount == 1 && announcement == null && gameSheet.areAllNonAnnouncementColumnsCompleted;
        }
        private set;
    }
    
    public void rollDice(Integer[] diceToRoll) {
        validateRollAction();
        // always roll all dice for the first roll
        if (rollCount == 0) {
            for (Dice dice : dices) {
                dice.roll();
            }
        } else {
            for (Integer index : diceToRoll) {
                Dice dice = dices.get(index);
                dice.roll();
            }
        }
        rollCount += 1;
    }

    public Integer[] diceValues {
        get {
            Integer[] diceValues = new Integer[GameConstants.DICE_LIMIT];
            for(Dice dice : dices) {
                diceValues.add(dice.value);
            }
            return diceValues;
        }
        private set;
    }
    
    public void fillBox(ColumnType cType, BoxType bType) {
        validateFillBoxAction(cType, bType);
        gameSheet.fillBox(cType, bType, ScoreCalculator.calculateScore(diceValues, bType));
        if (gameSheet.isCompleted) {
            status = GameStatus.FINISHED;
        }
        rollCount = 0;
        announcement = null;
    }
    
    public void makeAnnouncement(BoxType bType) {
        validateAnnouncementAction(bType);
        announcement = bType;
    }

    public void restart() {
        validateRestartAction();
        rollCount = 0;
        announcement = null;
        gameSheet = Sheet.getInstance();
        dices = generateDices();
    }

    private void validateRollAction() {
        if (rollCount == 3) {
            throw new RollLimitExceededException(MessageConstants.ERROR_ROLL_LIMIT_EXCEEDED);
        } else if (isAnnouncementRequired) {
            throw new AnnouncementRequiredException(MessageConstants.ERROR_ANNOUNCEMENT_REQUIRED);
        }
    }

    private void validateFillBoxAction(ColumnType cType, BoxType bType) {
        if (rollCount == 0) {
			throw new DiceRollRequiredException(MessageConstants.ERROR_DICE_ROLL_REQUIRED);
        } else if (!isBoxAvailable(cType, bType)) {
            throw new BoxUnavailableException(MessageConstants.ERROR_BOX_NOT_AVAILABLE);
        }
    }

    private void validateAnnouncementAction(BoxType bType) {
        if (announcement != null) {
            throw new AnnouncementAlreadyDeclaredException(MessageConstants.ERROR_ANNOUNCEMENT_ALREADY_DECLARED);
        } else if (rollCount == 0) {
            throw new DiceRollRequiredException(MessageConstants.ERROR_DICE_ROLL_REQUIRED);
        } else if (rollCount > 1) {
            throw new AnnouncementUnavailableException(MessageConstants.ERROR_ANNOUNCEMENT_NOT_AVAILABLE);
        }
    }

    private void validateRestartAction() {
        if (status == GameStatus.FINISHED) {
            throw new RestartFinishedGameException(MessageConstants.ERROR_RESTART_FINISHED_GAME);
        }
    }

    
    private Boolean isBoxAvailable(ColumnType cType, BoxType bType) {
        if (gameSheet.columns.get(cType.ordinal()).boxes.get(bType.ordinal()).value != null) {
            return false;
        }   
        if (cType == ColumnType.FREE) {
            return true;
        } else if (cType == ColumnType.DOWNWARDS) {
            return bType == BoxType.ONES || gameSheet.columns.get(cType.ordinal()).boxes.get(bType.ordinal() - 1).value != null;
        } else if (cType == ColumnType.UPWARDS) {
            return bType == BoxType.YAMB || gameSheet.columns.get(cType.ordinal()).boxes.get(bType.ordinal() + 1).value != null;
        } else if (cType == ColumnType.ANNOUNCEMENT) {
            return bType == announcement;
        }
        return false;
    }
}