force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <label>Announcement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Box_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game__c/fields/Roll_Count__c.field-meta.xml
<CustomField>
    <fullName>Roll_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Roll Count</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Sheet__c.field-meta.xml
<CustomField>
    <fullName>Sheet__c</fullName>
    <defaultValue>&apos;{}&apos;</defaultValue>
    <label>Sheet</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Score__c/Score__c.object-meta.xml
<CustomObject>
    <label>Score</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Score Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Box_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ONES</fullName>
        <label>Ones</label>
    </customValue>
    <customValue>
        <fullName>TWOS</fullName>
        <label>Twos</label>
    </customValue>
    <customValue>
        <fullName>THREES</fullName>
        <label>Threes</label>
    </customValue>
    <customValue>
        <fullName>FOURS</fullName>
        <label>Fours</label>
    </customValue>
    <customValue>
        <fullName>FIVES</fullName>
        <label>Fives</label>
    </customValue>
    <customValue>
        <fullName>SIXES</fullName>
        <label>Sixes</label>
    </customValue>
    <customValue>
        <fullName>MAX</fullName>
        <label>Max</label>
    </customValue>
    <customValue>
        <fullName>MIN</fullName>
        <label>Min</label>
    </customValue>
    <customValue>
        <fullName>TRIPS</fullName>
        <label>Trips</label>
    </customValue>
    <customValue>
        <fullName>STRAIGHT</fullName>
        <label>Straight</label>
    </customValue>
    <customValue>
        <fullName>BOAT</fullName>
        <label>Boat</label>
    </customValue>
    <customValue>
        <fullName>CARRIAGE</fullName>
        <label>Carriage</label>
    </customValue>
    <customValue>
        <fullName>YAMB</fullName>
        <label>Yamb</label>
    </customValue>
    <masterLabel>Box Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/api/GameService.cls
public class GameService {

    public Game getGameByRecordId(Id gameId) {
        System.debug(gameId);
        Game__c gameRecord = getRecordById(gameId);
        Game gameObj = new Game();
        gameObj.mapFromSObject(gameRecord);
        return gameObj;
    }

    public Game rollDiceById(Id gameId, ActionRequest actionRequest) {
        System.debug(actionRequest);
        Game game = getGameByRecordId(gameId);
        game.rollDice(actionRequest.diceToRoll);
        Game__c gameRecord = new Game__c(Id = gameId);
        gameRecord = game.mapToSObject(gameRecord); 
        update gameRecord;
        return game;
    }

    public Game makeAnnouncementById(Id gameId, ActionRequest actionRequest) {
        System.debug(actionRequest);
        Game game = getGameByRecordId(gameId);
        game.makeAnnouncement(actionRequest.bType);
        Game__c gameRecord = new Game__c(Id = gameId);
        gameRecord = game.mapToSObject(gameRecord); 
        update gameRecord;
        return game;
    }

    public Game fillBoxById(Id gameId, ActionRequest actionRequest) {
        System.debug(actionRequest);
        Game game = getGameByRecordId(gameId);
        game.fillBox(actionRequest.cType, actionRequest.bType);
        if (game.status == GameStatus.FINISHED) {
            // Score__c score = new Score__c(
            //     game.sheet.totalSum
            // );
            // insert score;
        }
        Game__c gameRecord = new Game__c(Id = gameId);
        gameRecord = game.mapToSObject(gameRecord); 
        update gameRecord;
        return game;
    }

    public Game restartById(Id gameId) {
        Game game = getGameByRecordId(gameId);
        game.restart();
        Game__c gameRecord = new Game__c(Id = gameId);
        gameRecord = game.mapToSObject(gameRecord); 
        update gameRecord;
        return game;
    }

    private Game__c getRecordById(Id gameId) {
        return [
            SELECT 
                Id, Roll_Count__c, Announcement__c, 
                Sheet__c, Dices__c, Status__c 
            FROM Game__c 
            WHERE Id = :gameId
        ];
    }


}